// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsO_x9N8lMBzNWK-DKXGgsrgyRIbIBR-U',
    appId: '1:993615950310:web:17d4e354dcedb9763da627',
    messagingSenderId: '993615950310',
    projectId: 'skinyapp',
    authDomain: 'skinyapp.firebaseapp.com',
    storageBucket: 'skinyapp.appspot.com',
    measurementId: 'G-71F6TVNBG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxlHpE3uwcijXz6-_4ffntZ4rbHIQBDps',
    appId: '1:993615950310:android:1ae1071b73123e003da627',
    messagingSenderId: '993615950310',
    projectId: 'skinyapp',
    storageBucket: 'skinyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxqfM6jIBoSuCJdg8Lk-URdoZAcvb60M',
    appId: '1:993615950310:ios:bd4292491eac85483da627',
    messagingSenderId: '993615950310',
    projectId: 'skinyapp',
    storageBucket: 'skinyapp.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIxqfM6jIBoSuCJdg8Lk-URdoZAcvb60M',
    appId: '1:993615950310:ios:a382d586ce69ec883da627',
    messagingSenderId: '993615950310',
    projectId: 'skinyapp',
    storageBucket: 'skinyapp.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
